### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by travisbutton** [23d1/Arnold-to-Redshift#1]
I'm getting this error with you script, any chance you've encountered this or possibly know what I could do to fix it?

# Error: ValueError: file <maya console> line 329: No object matches name: aiStandard1SG.RedshiftMaterial

Thank you!

**Comment by 23d1** [comment]
Yeah, that usually means you're using the old (below Arnold 5.0) Arnold Standard Material. The script only converts aiStandardSurface (the 5.0+ standard material). One way around this is to first run Arnold's conversion script (from the Arnold menu), then run the Arnold-to-Redshift script.

Let me know if that works.

**Comment by travisbutton** [comment]
Thanks so much for the very quick reply.  This Standard-->StandardSurface  must be a Maya2018 feature yeah?  I'm still in Maya 2017 and don't happen to see it.  A stock model I bought came setup as Arnold so I was looking for a quick solution to convert over to RS but it seems as if I may as well just do it manually and rebuild the shaders.  Thanks for your input, and for this script!

**Comment by 23d1** [comment]
In that case, you just need to update Arnold, which you can do at https://www.solidangle.com/arnold/download/
MtoA 3.0.1.1 (which installs the Arnold 5.1.1.1 core) is the latest at this moment. Once you've updated, you should have that option in the Arnold menu.

**Comment by travisbutton** [comment]
Thanks for the followup.  This was what I needed.  Appreciate the script and the extra insight.

**Comment by 23d1** [comment]
Right on! Cheers.
